# name: Automerge

# on:
#   schedule:
#     - cron: 0 * * * *
    
#   pull_request_target:
#     types:
#       - opened
#       - synchronized
#       - reopened
#       - edited
#       - labeled
#       - unlabeled
#       - ready_for_review

#   workflow_dispatch:
#     inputs:
#       pull-request:
#         description: Pull Request Number
#         required: false

# jobs:
#   automerge:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: reitermarkus/automerge@v1.5.2
#         with:
#           token: ${{ secrets.TOKEN }}
#           pull-request: ${{ github.event.inputs.pull-request }}
