name: Automerge

on:
  pull_request:

  schedule:
    - cron: 0 * * * *
    
  pull_request_target:
    types:
      - opened

  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1.5.2
        with:
          token: ${{ secrets.TOKEN }}
          pull-request: ${{ github.event.inputs.pull-request }}
