name: Dependabot Merge

on:
  pull_request_target:
    types:
      - opened
      
  workflow_dispatch:

jobs:
  dependabot-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - uses: peter-evans/find-comment@v1
        id: find-comment
        with:
          token: ${{ secrets.TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: '@dependabot merge'
      - uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.TOKEN }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: '@dependabot merge'
          edit-mode: replace
